[project]
name = 'Decentralized-Public-Postal-and-Mail-Services-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mail-forwarding]
path = 'contracts/mail-forwarding.clar'
clarity_version = 2
epoch = 2.5

[contracts.mail-routing]
path = 'contracts/mail-routing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
